version: "3.9"
services:
  dependencies:
    image: ${LPM_PROJECT_DOCKERHUB:?err}/libpointmatcher-dependencies:${LPM_IMAGE_TAG:?err}
    build:
      context: ..
      dockerfile: ./build_system/ubuntu/Dockerfile.dependencies
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}
        LPM_INSTALLED_LIBRARIES_PATH: ${LPM_INSTALLED_LIBRARIES_PATH:?err}
        LPM_LIBPOINTMATCHER_SRC_REPO_NAME: ${LPM_LIBPOINTMATCHER_SRC_REPO_NAME:?err}
#  # ToDo: on task end >> unmute next bloc ↓↓
#  libpointmatcher:
#    image: ${LPM_PROJECT_DOCKERHUB:?err}/libpointmatcher:${LPM_IMAGE_TAG:?err}
#    build:
#      context: ..
#      dockerfile: ./build_system/ubuntu/Dockerfile.libpointmatcher
#      args:
#        PROJECT_HUB: ${LPM_PROJECT_DOCKERHUB}
#        BASE_IMAGE: libpointmatcher-dependencies
#        BASE_IMAGE_TAG: ${LPM_IMAGE_TAG}
#        LPM_VERSION: ${LPM_VERSION:?err}
#    depends_on:
#      - dependencies
